title: Status Page - WildanFauzy.com
buildFuture: true
defaultContentLanguage: id
languageCode: id
baseURL: https://status.wildanfauzy.com/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Beranda
      category: Bandung, Indonesia
      description: Halaman Beranda Website
    - name: Perpus
      category: Bandung, Indonesia
      description: Perpustakaan Online
    - name: Blog
      category: Bandung, Indonesia
      description: Halaman blog yang berisikan tulisan
    - name: Jurnal
      category: New Jersey
      description: Jurnal Online powered by medium.com
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: black
  logo: logo.png
  incidentPostsPerPage: 2
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Bandung, Indonesia
      description: The main servers are located here.
      closed: false
    - name: New Jersey
      description: Medium.com's server here.
      closed: true
  description:Kami terus memantau status layanan kami dan jika ada
    setiap gangguan, catatan akan diposting di sini.
  enableCustomHTML: true
  useLargeHeaderDesign: false
